name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  english_words: ^3.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Regular.ttf
        - asset: assets/font/Nunito-Bold.ttf
        - asset: assets/font/Nunito-Light.ttf
        - asset: assets/font/Nunito-Black.ttf
        - asset: assets/font/Nunito-ExtraLight.ttf
        - asset: assets/font/Nunito-SemiBold.ttf
  assets:
    - assets/image/login.png
    - assets/image/login2.png